### PR TITLE
Rename & migrate `representative_plugin` as namespace plugin

### PR DESCRIPTION
**Pull request by justinmayer**
See: https://github.com/getpelican/pelican-plugins/issues/1390

### CODE REVIEW

**Comment by justinmayer** [comment]
@schtobia replied to [my comment](https://github.com/getpelican/pelican-plugins/issues/1390#issuecomment-1669905818) about [tests not passing](https://github.com/pelican-plugins/featured-image/actions/runs/5799244846/job/15718820605?pr=1) for the Representative Image plugin, even in the monolithic repo, even before any rename/migration-related changes were made, and @schtobia said:

> Hmm, it seems there is a problem I could use some help with.
> 
> It seems like the `register()` function is successfully connected on `all_generators_finalized`, but the registered function is never called, at least in the test environment.
> 
> Could you please give me some directions where to look further?

I have never used this plugin, and I'm away from my computer for the next few days. So I am ill-equipped to delve into this topic in detail at the moment.

@khuevu @jkrshw @murchik @kernc @Lucas-C @pauloxnet: As folks who have contributed to this plugin in the past, might you have a moment to take a look and help @schtobia fix the failing tests? (cc: @avaris also, in case he has a moment)

**Comment by avaris** [comment]
I pushed a commit to fix the tests. The old version of tests would've never worked with the new signal. It connects the signals but the way tests are configured, it would never hit that signal, tests would need to actually run `pelican`. But that's not needed and changed the tests to only test the functionality.

However, `pelican` possibly needs a way to reliably get and set `summary`. Currently I don't think this plugin would be working "correctly". It's supposed to delete the images from `summary` but these modifications will not be propagated due to the caching of `summary`.

**Comment by justinmayer** [comment]
@avaris: Many thanks for fixing the tests. Let's create a new issue to track whether Pelican needs a way to get and set `summary` in a reliable manner.

Many thanks also to @khuevu for creating this plugin, to @schtobia for helping migrate it to its new home, and to all the folks who have contributed to the development of this plugin.

Featured Image: https://github.com/pelican-plugins/featured-image/releases/tag/1.0.0 ✨

**Comment by schtobia** [comment]
Thanks @avaris @justinmayer!

**Pull request merged**
